spring:
  application:
    name: building-diary

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: building-diary-client
            client-secret: IGm1CRdduJgUTmfqAeE6JjbiU2gBUN5r
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/building-diary
            user-name-attribute: preferred_username

  datasource:
    url: jdbc:postgresql://localhost:5432/building_diary
    username: building_diary
    password: building_diary
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  data:
    redis:
      host: localhost
      port: 6379

  session:
    store-type: redis
    data:
      redis:
        namespace: building-diary:session

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: building-diary
    client-id: building-diary-admin
    client-secret: JnP5M2xjPAWAoxaN7u32lfiWFhCJgGEa
    target-realm: building-diary
    default-role: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
