version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:25.0
    working_directory: ~/project

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-deps-{{ checksum "build.gradle.kts" }}-{{ checksum "building-diary-core/build.gradle.kts" }}-{{ checksum "photos-service/build.gradle.kts" }}
            - gradle-deps-
      - run:
          name: Build project
          command: ./gradlew build -x test
      - save_cache:
          key: gradle-deps-{{ checksum "build.gradle.kts" }}-{{ checksum "building-diary-core/build.gradle.kts" }}-{{ checksum "photos-service/build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - persist_to_workspace:
          root: .
          paths:
            - building-diary-core/build
            - photos-service/build

  test:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-deps-{{ checksum "build.gradle.kts" }}-{{ checksum "building-diary-core/build.gradle.kts" }}-{{ checksum "photos-service/build.gradle.kts" }}
            - gradle-deps-
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: ./gradlew test
      - store_test_results:
          path: building-diary-core/build/test-results/test
      - store_test_results:
          path: photos-service/build/test-results/test
      - store_artifacts:
          path: building-diary-core/build/reports/tests/test
          destination: core-test-reports
      - store_artifacts:
          path: photos-service/build/reports/tests/test
          destination: photos-test-reports

workflows:
  build-and-test:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build
      - test:
          requires:
            - build

  main:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build
      - test:
          requires:
            - build
